---
# Ansible Collection requirments to pull modules down
# file /collections/requirements.yml used by ansible by Ansible Automation Platform
# v0.001 20210804
# Documenation: https://www.ansible.com/blog/installing-and-using-collections-on-ansible-tower  


collections:
  - name: cisco.nxos #  https://docs.ansible.com/ansible/latest/collections/cisco/nxos/index.html   pull from top name  https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_config_module.html#ansible-collections-cisco-nxos-nxos-config-module  
    version: 2.5.0

