---
# This enables ansible / bastion host to use ansible gloabal groups to enable passwordless login with assumption that user on host is set with "ansible" user and password
# v0.002 2021011249
# file: /roles/role_ssh_passwordless_login.yml
# How to run: Ex for one host: ansible-playbook ssh_passwordless_login.yml --limit thor

- name: SSH password login for first time for list of hosts
  hosts: all
  tasks:
    - name: Deploy SSH Key
      authorized_key: 
        user: ansible
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
        state: present
