---
# Deploy VMs per the provided HCI cluster via oVirt engine. Goal create new VM with basic input of hostname and optional IP and template name. Default image CentOS 8 streams
# v0.001 20210218
# file: /roles/task_ovirt_new_vm.yml 
# <<<<<<<<<DRAFT>>>>>>>>>>>

# Connect to oVirt and validate template ready



# Use collected user input of hostname


# Lookup via DNS vm name and either continue or fail due to lack of DNS



# Create VM via calls to oVirt engine