---
# This role does reboot now, waits 60 seconds, and tries to run whoami to check success.
# v1.0 202100218
# file: /roles/role_selinux_disable.yml

- name: Rebooting hosts "{{ target_hosts }}"
  reboot:
    msg: "Reboot initiatedd"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
